name: Build Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-mac:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build the Electron app for macOS
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          export PYTHON=$(which python3)
          npm run dist:mac

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v2
        with:
          name: electron-app-mac
          path: dist/

  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build the Electron app for Windows
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PYTHON: python
        run: npm run dist:win

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v2
        with:
          name: electron-app-windows
          path: dist/
